services:
  app:
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    image: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    env_file:
      # NOTE: the DJANGO_PORT in .env.prod must differ from Nginx host (8000) and container (80) ports
      - .env.prod
    ports:
      - "8000:80" # *:{<1024} for rootful Podman machine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/usr/share/nginx/html/static
    networks:
      - app_network
    depends_on:
      - app

volumes:
  static_volume: # Declare volume for static files
