services:
  app:
    build:
      context: . # Build the image from the current directory
      dockerfile: Dockerfile # Use the Dockerfile in the current directory for the build
    image: django_weather_app
    env_file:
      - .env.prod
    networks:
      - app_network
    command: >
      sh -c "
      uv run --no-dev manage.py migrate; 
      uv run --no-dev manage.py collectstatic --noinput --clear;
      uv run --no-dev manage.py createsuperuser --noinput;
      uv run --no-dev gunicorn config.asgi:application
      "

networks:
  # Define custom networks for services to communicate
  app_network:
    driver: bridge # Use the default 'bridge' network driver
    labels:
      com.docker.compose.network: app_network
