services:
  app:
    build:
      context: . # Build the image from the current directory
      dockerfile: Dockerfile # Use the Dockerfile in the current directory for the build
    image: django_weather_app
    env_file:
      - .env.prod
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
    volumes:
      - ./certs/weather.com-key.pem:/etc/ssl/certs/weather.com-key.pem
      - ./certs/weather.com-cert.pem:/etc/ssl/certs/weather.com-cert.pem
    networks:
      - app_network
    command: >
      sh -c "
      uv run --no-dev manage.py migrate; 
      uv run --no-dev server.py; 
      "

networks:
  # Define custom networks for services to communicate
  app_network:
    driver: bridge # Use the default 'bridge' network driver
    labels:
      com.docker.compose.network: app_network
