services:
  app:
    environment:
      DJANGO_REDIS: True
    depends_on:
      - redis

  redis:
    # Redis service for caching
    image: redis:alpine # Use the official Redis image based on Alpine
    volumes:
      - redis_data:/data # Persist Redis data in a Docker volume (optional, depends on use case)
    networks:
      - app_network # Ensure that the caching service is on the same network

volumes:
  # Declare volumes that are used for persistent data storage
  redis_data: # This volume is used by the 'caching' service to store Redis data (optional)
