# Generated by Django 5.1.4 on 2025-02-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="city",
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
